In [1]:
import numpy as np

In [14]:
# arr creation
arr1 = np.random.randint(1, 10, size=(3, 3))
arr2 = np.random.randint(1, 10, size=(5, 3))
print('array 1:\n', arr1)
print('array 2:\n', arr2)

array 1:
 [[3 4 9]
 [7 8 7]
 [6 2 6]]
array 2:
 [[8 7 8]
 [4 5 8]
 [5 5 7]
 [1 5 2]
 [5 5 4]]


In [19]:
# concatenation
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# For concatenation in axis 0, the number of columns must be the same.
# If the number of columns is different, a ValueError will be raised.
# a ValueError will be raised.

[[3 4 9]
 [7 8 7]
 [6 2 6]
 [8 7 8]
 [4 5 8]
 [5 5 7]
 [1 5 2]
 [5 5 4]]


In [22]:
# Transpose is a method that changes the shape of an array.
transposed_arr3 = arr3.T
transposed_arr3

array([[3, 7, 6, 8, 4, 5, 1, 5],
       [4, 8, 2, 7, 5, 5, 5, 5],
       [9, 7, 6, 8, 8, 7, 2, 4]])