In [1]:
import numpy as np

In [11]:
# matrix creation

matrix1 = np.linspace(1, 10, 100, dtype=float).reshape(10, 10)
matrix1

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
         1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182],
       [ 1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
         2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273],
       [ 2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
         3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364],
       [ 3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
         4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455],
       [ 4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
         5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545],
       [ 5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
         6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636],
       [ 6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
         6.90909091,  7.        ,  7.09090909

In [13]:
# print bool matrix with condition
bool_matrix = matrix1 > 5
bool_matrix

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [14]:
# conditions doesnt change the original matrix
matrix1

array([[ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
         1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182],
       [ 1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
         2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273],
       [ 2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
         3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364],
       [ 3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
         4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455],
       [ 4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
         5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545],
       [ 5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
         6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636],
       [ 6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
         6.90909091,  7.        ,  7.09090909

In [15]:
bool_matrix_and = (matrix1 > 2) & (matrix1 < 8)
bool_matrix_and

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [18]:
arr2 = np.random.randint(-10, 10, size=(10,10))
arr2

array([[  4,  -4,   9,  -2,  -1,   7,  -7,   7,   8,   3],
       [ -3,   9,   2, -10,  -3,   7, -10,  -8,  -6,   7],
       [ -9,  -2,   4,   6,  -8,  -4,   1,   0,  -1,   6],
       [  9,  -5,  -8,   3,  -8,   8,   9,  -1,  -6,  -5],
       [  7,  -7,   8,  -8,   9,   5,  -6,  -7, -10,   1],
       [ -4,   0,  -4,  -9,  -2, -10,  -1,   8,  -7,  -8],
       [ -4,   8,   7,  -7,   5,   9,   3,   7,  -8,  -7],
       [  0,   6,  -8,   4,   2,   4,  -6,   4,   6,  -3],
       [  9,  -6,   0,  -5,   8,  -3,  -9,   8,  -1,   8],
       [  5,   1,  -7,   4,  -9,  -6,  -9,   5,  -5,   6]])

In [19]:
# catching if there are negaticve values
bool_neg_arr2 = arr2 < 0
print(bool_neg_arr2)

[[False  True False  True  True False  True False False False]
 [ True False False  True  True False  True  True  True False]
 [ True  True False False  True  True False False  True False]
 [False  True  True False  True False False  True  True  True]
 [False  True False  True False False  True  True  True False]
 [ True False  True  True  True  True  True False  True  True]
 [ True False False  True False False False False  True  True]
 [False False  True False False False  True False False  True]
 [False  True False  True False  True  True False  True False]
 [False False  True False  True  True  True False  True False]]


In [25]:
bool_neg_arr2[0:25]
bool_neg_arr2

array([[False,  True, False,  True,  True, False,  True, False, False,
        False],
       [ True, False, False,  True,  True, False,  True,  True,  True,
        False],
       [ True,  True, False, False,  True,  True, False, False,  True,
        False],
       [False,  True,  True, False,  True, False, False,  True,  True,
         True],
       [False,  True, False,  True, False, False,  True,  True,  True,
        False],
       [ True, False,  True,  True,  True,  True,  True, False,  True,
         True],
       [ True, False, False,  True, False, False, False, False,  True,
         True],
       [False, False,  True, False, False, False,  True, False, False,
         True],
       [False,  True, False,  True, False,  True,  True, False,  True,
        False],
       [False, False,  True, False,  True,  True,  True, False,  True,
        False]])