In [1]:
import numpy as np

In [ ]:
# matrix creation

matrix1 = np.linspace(1, 10, 100, dtype=float).reshape(10, 10)
matrix1

In [ ]:
# print bool matrix with condition
bool_matrix = matrix1 > 5
bool_matrix

In [ ]:
# conditions doesnt change the original matrix
matrix1

In [ ]:
bool_matrix_and = (matrix1 > 2) & (matrix1 < 8)
bool_matrix_and

In [ ]:
arr2 = np.random.randint(-10, 10, size=(10,10))
arr2

In [ ]:
# catching if there are negaticve values
bool_neg_arr2 = arr2 < 0
print(bool_neg_arr2)

In [ ]:
bool_neg_arr2[0:25]
bool_neg_arr2

In [6]:
# division by zero
matrix2 = np.random.randint(-10, 10+1, size=(10,10))
print(matrix2)

# here we execute the opperation for the matrix elements
divided_by_zero = 1 / matrix2
print(divided_by_zero)
# those values who are 1 / 0 are inf

[[ -2  -7  -8   3   3  -8   0   0   4  -7]
 [ -3   3  -5  -6  10  -2   3   1   9   7]
 [  4   9   2  -5 -10   9  10  -1   3  -8]
 [ -7   2  -7  -5   3   2  -7  -2   8  -3]
 [  8  -2 -10   8   1  -5 -10  -2  -2   7]
 [ -1  -8   4   1   8   0  -4  -2  -5  -8]
 [  6  -2  -4  -1   6  -3  -5   1  -1   2]
 [-10   3  -8   9   0  10  -1   4 -10   4]
 [ -6  -9   0  -2   7  -3  -5   1  10   8]
 [  5   1  -1   7   4  -2  -3  -5   5   6]]
[[-0.5        -0.14285714 -0.125       0.33333333  0.33333333 -0.125
          inf         inf  0.25       -0.14285714]
 [-0.33333333  0.33333333 -0.2        -0.16666667  0.1        -0.5
   0.33333333  1.          0.11111111  0.14285714]
 [ 0.25        0.11111111  0.5        -0.2        -0.1         0.11111111
   0.1        -1.          0.33333333 -0.125     ]
 [-0.14285714  0.5        -0.14285714 -0.2         0.33333333  0.5
  -0.14285714 -0.5         0.125      -0.33333333]
 [ 0.125      -0.5        -0.1         0.125       1.         -0.2
  -0.1        -0.5   

C:\Users\damal\AppData\Local\Temp\ipykernel_6740\820668895.py:4: RuntimeWarning: divide by zero encountered in divide
  divided_by_zero = 1 / matrix2
