In [2]:
import numpy as np

In [3]:
# ndarray is a n dimensional array object, fast and flexible
# container for large datasets in python

In [5]:
# generate some rdm data
data = np.random.randn(8, 5)
data_type = data.dtype
print(data, data_type)

[[ 1.47798435  0.22514913  0.83094859 -0.77236277  1.09185864]
 [ 0.51890626  0.25208897 -0.09320131 -0.69349717 -0.10750955]
 [-1.15917408 -0.33671497 -0.03291107  0.10422989  0.08135207]
 [ 0.33348565  0.43312899  0.01269136  0.25572726 -2.04327534]
 [-1.24382227  0.85168954  0.07608358 -0.44577527 -0.71765641]
 [ 0.88258634  1.15947357 -1.06775028 -1.2815916   0.5132379 ]
 [-0.1584694   0.31542889  0.96190148  1.11826483  0.35076543]
 [ 0.0937093   0.46483266  0.9128175   0.31505915  0.42521423]] float64


In [8]:
# aggregation functions
# sum by axis
sum_data_rows = np.sum(data, axis=1)
sum_data_columns =np.sum(data, axis=0)
print('The sum of rows is: ', sum_data_rows, '\nThe sum of columns is: ', sum_data_columns)

The sum of rows is:  [ 2.85357794 -0.12321279 -1.34321816 -1.00824209 -1.47948083  0.20595593
  2.58789123  2.21163285] 
The sum of columns is:  [ 0.74520616  3.36507679  1.60057985 -1.39994568 -0.40601304]


In [10]:
# array attributes

print('The shape of data is: ', data.shape, '\nThe dimension of data is: ', data.ndim, '\nThe data type of data is: ', data.dtype, '\nThe size of data is: ', data.size)	

The shape of data is:  (8, 5) 
The dimension of data is:  2 
The data type of data is:  float64 
The size of data is:  40
