In [2]:
import numpy as np

In [ ]:
# create a 8x8 matrix with random integers from -100 to 100 
matrix1 = np.random.randint(-100, 101, size=(8, 8))
matrix1

In [ ]:
# bool matrix with bools > -25
greater_than_min25_num = matrix1 > -25
print(greater_than_min25_num)

In [ ]:
# opperatig with matrix elements
matrix1_product = matrix1 * -0.333
print(matrix1_product)

In [ ]:
# opperation between matrices
matrix2 = matrix1 + matrix1_product
print(matrix2)

In [ ]:
# sorted matrix axis 1
sorted_matrix = np.sort(matrix2, axis=1)
sorted_matrix

In [ ]:
# sorted matrix axis 0
sorted_matrix_zero_axis = np.sort(matrix2, axis=0)
sorted_matrix_zero_axis

In [3]:
# randn() method productes numbers sampled from a standard normal distribution
# Theoretically: No minimum or maximum limit.
# Practically: The range of values is unbounded, but values further
# away from 0 become increasingly rare.
data = np.random.randn(2,3)
print(data)

[[-1.01137134 -0.182087   -0.15953201]
 [ 0.2795801  -1.77559215 -0.07206091]]


In [4]:
# multiply data by 1.618
data_product = data * 1.618
print(data_product)

[[-1.63639882 -0.29461677 -0.25812279]
 [ 0.45236061 -2.8729081  -0.11659456]]


In [5]:
# get the shape of the ndim arra
print(data.shape)


(2, 3)