In [1]:
#import numpy library
import numpy as np

In [6]:
arr1 = np.random.randint(1, 100, (9,10))
arr1

array([[95, 47, 18, 37, 17, 44, 74, 79, 35, 33],
       [78, 81, 11, 88,  2, 32, 95, 46, 33, 65],
       [54, 86, 39, 93,  9, 14, 66, 68, 88, 44],
       [98, 30, 30, 86, 88,  6, 35, 85, 34, 29],
       [32, 43, 69, 46, 60, 31, 11, 81, 20, 14],
       [10, 67, 69, 72, 50, 89,  1, 32, 41, 41],
       [93, 85, 21,  5, 72, 48, 32, 21,  7, 13],
       [64, 40, 95,  5, 60, 98, 93, 34, 18, 36],
       [89, 45, 86, 30, 62, 68,  7, 49, 37, 77]])

In [7]:
# .shape is a tuple that gives dimensions of the array
arr1.shape

(9, 10)

In [8]:
# .ndim gives the number of dimensions of the array
arr1.ndim

2

In [10]:
# .reshape reshapes the array
# 90 = 2 * 3 * 3 * 5
arr1.reshape(6,15)

array([[95, 47, 18, 37, 17, 44, 74, 79, 35, 33, 78, 81, 11, 88,  2],
       [32, 95, 46, 33, 65, 54, 86, 39, 93,  9, 14, 66, 68, 88, 44],
       [98, 30, 30, 86, 88,  6, 35, 85, 34, 29, 32, 43, 69, 46, 60],
       [31, 11, 81, 20, 14, 10, 67, 69, 72, 50, 89,  1, 32, 41, 41],
       [93, 85, 21,  5, 72, 48, 32, 21,  7, 13, 64, 40, 95,  5, 60],
       [98, 93, 34, 18, 36, 89, 45, 86, 30, 62, 68,  7, 49, 37, 77]])

In [21]:
# we can reshape the array to a higher dimension tensor
arr1.reshape(3,2,3,5)

array([[[[95, 47, 18, 37, 17],
         [44, 74, 79, 35, 33],
         [78, 81, 11, 88,  2]],

        [[32, 95, 46, 33, 65],
         [54, 86, 39, 93,  9],
         [14, 66, 68, 88, 44]]],


       [[[98, 30, 30, 86, 88],
         [ 6, 35, 85, 34, 29],
         [32, 43, 69, 46, 60]],

        [[31, 11, 81, 20, 14],
         [10, 67, 69, 72, 50],
         [89,  1, 32, 41, 41]]],


       [[[93, 85, 21,  5, 72],
         [48, 32, 21,  7, 13],
         [64, 40, 95,  5, 60]],

        [[98, 93, 34, 18, 36],
         [89, 45, 86, 30, 62],
         [68,  7, 49, 37, 77]]]])

In [ ]:
# by default, reshape() uses C-style ordering
# error occurs if the new shape does not match the original shape