In [2]:
# import libraries
import pandas as pd
import numpy as np


In [3]:
# array creation
arr = np.linspace(0, 13, 100)
arr

array([ 0.        ,  0.13131313,  0.26262626,  0.39393939,  0.52525253,
        0.65656566,  0.78787879,  0.91919192,  1.05050505,  1.18181818,
        1.31313131,  1.44444444,  1.57575758,  1.70707071,  1.83838384,
        1.96969697,  2.1010101 ,  2.23232323,  2.36363636,  2.49494949,
        2.62626263,  2.75757576,  2.88888889,  3.02020202,  3.15151515,
        3.28282828,  3.41414141,  3.54545455,  3.67676768,  3.80808081,
        3.93939394,  4.07070707,  4.2020202 ,  4.33333333,  4.46464646,
        4.5959596 ,  4.72727273,  4.85858586,  4.98989899,  5.12121212,
        5.25252525,  5.38383838,  5.51515152,  5.64646465,  5.77777778,
        5.90909091,  6.04040404,  6.17171717,  6.3030303 ,  6.43434343,
        6.56565657,  6.6969697 ,  6.82828283,  6.95959596,  7.09090909,
        7.22222222,  7.35353535,  7.48484848,  7.61616162,  7.74747475,
        7.87878788,  8.01010101,  8.14141414,  8.27272727,  8.4040404 ,
        8.53535354,  8.66666667,  8.7979798 ,  8.92929293,  9.06

In [4]:
# slicing 
arr_zeros = arr[8:28]
arr_zeros

array([1.05050505, 1.18181818, 1.31313131, 1.44444444, 1.57575758,
       1.70707071, 1.83838384, 1.96969697, 2.1010101 , 2.23232323,
       2.36363636, 2.49494949, 2.62626263, 2.75757576, 2.88888889,
       3.02020202, 3.15151515, 3.28282828, 3.41414141, 3.54545455])

In [5]:
# array modification
arr_zeros[:] = 0
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [8]:
arr

array([ 0.        ,  0.13131313,  0.26262626,  0.39393939,  0.52525253,
        0.65656566,  0.78787879,  0.91919192,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  3.67676768,  3.80808081,
        3.93939394,  4.07070707,  4.2020202 ,  4.33333333,  4.46464646,
        4.5959596 ,  4.72727273,  4.85858586,  4.98989899,  5.12121212,
        5.25252525,  5.38383838,  5.51515152,  5.64646465,  5.77777778,
        5.90909091,  6.04040404,  6.17171717,  6.3030303 ,  6.43434343,
        6.56565657,  6.6969697 ,  6.82828283,  6.95959596,  7.09090909,
        7.22222222,  7.35353535,  7.48484848,  7.61616162,  7.74747475,
        7.87878788,  8.01010101,  8.14141414,  8.27272727,  8.4040404 ,
        8.53535354,  8.66666667,  8.7979798 ,  8.92929293,  9.06

In [10]:
# slicing and creating a copy
arr1 = arr.copy()[5:25]
arr1

array([0.65656566, 0.78787879, 0.91919192, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [18]:
# conditions
hig_to_zero = arr1 > 0
hig_to_zero

False