In [1]:
import numpy as np

In [8]:
# arange generate a sequence of numbers
my_arr = np.arange(100)
arr2 = np.arange(66)
arr_steps = np.arange(0,666,6) # output: from 0 to 666 in steps 
print('my_arr: \n',my_arr)
print('arr2: \n',arr2)
print('arr_steps: \n', arr_steps)

my_arr: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
arr2: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65]
arr_steps: 
 [  0   6  12  18  24  30  36  42  48  54  60  66  72  78  84  90  96 102
 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192 198 204 210
 216 222 228 234 240 246 252 258 264 270 276 282 288 294 300 306 312 318
 324 330 336 342 348 354 360 366 372 378 384 390 396 402 408 414 420 426
 432 438 444 450 456 462 468 474 480 486 492 498 504 510 516 522 528 534
 540 546 552 558 564 570 576 582 588 594 600 606 612 618 624 630 636 642
 648 654 660]


In [12]:
# array function convert any sequence-like object and produces
# a numpy array
data3 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
data4 = [[2,4,6],[1,3,5],[7,11,13]]
# data5 = [None, 1, 'Hola parce',[1,9,18],{'a':'first element', 'b':77}]
arr3 = np.array(data3)
arr4 = np.array(data4)
# arr5 = np.array(data5) out: error
print('arr3: \n',arr3,'\narr4: \n',arr4)

# note: a list can contain different types of elements, but when 
# converting it into a np.array, the list must contain same type of
# elements, for efficiency.

arr3: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17] 
arr4: 
 [[ 2  4  6]
 [ 1  3  5]
 [ 7 11 13]]
