In [1]:
import numpy as np

In [3]:
# create a 8x8 matrix with random integers from -100 to 100 
matrix1 = np.random.randint(-10, 10+1, size=(8, 8))
print('matrix1: \n',matrix1)

matrix1: 
 [[  1  -3 -10  -2  -3  -1 -10  -9]
 [-10   0   8  -1   0  -5  -3  -3]
 [ -5 -10   7   3   5   0   3  -2]
 [  4   2   8   8   3  -5   8  -5]
 [ -3  10   7   2  -8  -6  -2  -6]
 [  6  -5   3  -5  -9  -6  -9   5]
 [ -7  -7   1  -1  -6   2  -6  -5]
 [ -4   9   2 -10  10   4  -2   3]]


In [7]:
# bool matrix with bools > -5
nums_greater_minus5 = matrix1 > -5
print('numbers > -5: \n',nums_greater_minus5)

numbers > -5: 
 [[ True  True False  True  True  True False False]
 [False  True  True  True  True False  True  True]
 [False False  True  True  True  True  True  True]
 [ True  True  True  True  True False  True False]
 [ True  True  True  True False False  True False]
 [ True False  True False False False False  True]
 [False False  True  True False  True False False]
 [ True  True  True False  True  True  True  True]]


In [8]:
# opperatig with matrix elements
matrix1_product = matrix1 * -0.333
print(matrix1_product)

[[-0.333  0.999  3.33   0.666  0.999  0.333  3.33   2.997]
 [ 3.33  -0.    -2.664  0.333 -0.     1.665  0.999  0.999]
 [ 1.665  3.33  -2.331 -0.999 -1.665 -0.    -0.999  0.666]
 [-1.332 -0.666 -2.664 -2.664 -0.999  1.665 -2.664  1.665]
 [ 0.999 -3.33  -2.331 -0.666  2.664  1.998  0.666  1.998]
 [-1.998  1.665 -0.999  1.665  2.997  1.998  2.997 -1.665]
 [ 2.331  2.331 -0.333  0.333  1.998 -0.666  1.998  1.665]
 [ 1.332 -2.997 -0.666  3.33  -3.33  -1.332  0.666 -0.999]]


In [9]:
# opperation between matrices
matrix2 = matrix1 + matrix1_product
print(matrix2)

[[ 0.667 -2.001 -6.67  -1.334 -2.001 -0.667 -6.67  -6.003]
 [-6.67   0.     5.336 -0.667  0.    -3.335 -2.001 -2.001]
 [-3.335 -6.67   4.669  2.001  3.335  0.     2.001 -1.334]
 [ 2.668  1.334  5.336  5.336  2.001 -3.335  5.336 -3.335]
 [-2.001  6.67   4.669  1.334 -5.336 -4.002 -1.334 -4.002]
 [ 4.002 -3.335  2.001 -3.335 -6.003 -4.002 -6.003  3.335]
 [-4.669 -4.669  0.667 -0.667 -4.002  1.334 -4.002 -3.335]
 [-2.668  6.003  1.334 -6.67   6.67   2.668 -1.334  2.001]]


In [12]:
# sorting matrixes (rows = axis 1, columns = axis 0)
sorted_matrix = np.sort(matrix2, axis=1)
sorted_matrix_zero_axis = np.sort(matrix2, axis=0) 
print('matrix2 sorted axis=1(rows): \n',sorted_matrix)
print('matrix2 sorted axis=0(columns): \n',sorted_matrix_zero_axis)



matrix2 sorted axis=1(rows): 
 [[-6.67  -6.67  -6.003 -2.001 -2.001 -1.334 -0.667  0.667]
 [-6.67  -3.335 -2.001 -2.001 -0.667  0.     0.     5.336]
 [-6.67  -3.335 -1.334  0.     2.001  2.001  3.335  4.669]
 [-3.335 -3.335  1.334  2.001  2.668  5.336  5.336  5.336]
 [-5.336 -4.002 -4.002 -2.001 -1.334  1.334  4.669  6.67 ]
 [-6.003 -6.003 -4.002 -3.335 -3.335  2.001  3.335  4.002]
 [-4.669 -4.669 -4.002 -4.002 -3.335 -0.667  0.667  1.334]
 [-6.67  -2.668 -1.334  1.334  2.001  2.668  6.003  6.67 ]]
matrix2 sorted axis=0(columns): 
 [[-6.67  -6.67  -6.67  -6.67  -6.003 -4.002 -6.67  -6.003]
 [-4.669 -4.669  0.667 -3.335 -5.336 -4.002 -6.003 -4.002]
 [-3.335 -3.335  1.334 -1.334 -4.002 -3.335 -4.002 -3.335]
 [-2.668 -2.001  2.001 -0.667 -2.001 -3.335 -2.001 -3.335]
 [-2.001  0.     4.669 -0.667  0.    -0.667 -1.334 -2.001]
 [ 0.667  1.334  4.669  1.334  2.001  0.    -1.334 -1.334]
 [ 2.668  6.003  5.336  2.001  3.335  1.334  2.001  2.001]
 [ 4.002  6.67   5.336  5.336  6.67   2.668  5.33

In [13]:
# randn() method productes numbers sampled from a standard normal distribution
# Theoretically: No minimum or maximum limit.
# Practically: The range of values is unbounded, but values further
# away from 0 become increasingly rare.
data = np.random.randn(2,3)
print(data)

[[ 0.25792118 -1.19178771 -1.58980549]
 [ 1.46858175  0.97061189  0.11274738]]


In [14]:
# multiply data by 1.618
data_product = data * 1.618
print(data_product)

[[ 0.41731647 -1.92831251 -2.57230528]
 [ 2.37616527  1.57045004  0.18242525]]


In [15]:
# get the shape of the ndim arra
print(data.shape)


(2, 3)


In [18]:
# product
arr3 = np.random.randint(1,10,(2,3))
print('array3: \n',arr3,'\n')
print('array3 * array3: \n', arr3 * arr3,'\n')
print('1 / array3: \n', (1 / arr3).round(2),'\n')
print('array3**0.5: \n', (arr3**0.5).round(1),'\n')

array3: 
 [[7 2 7]
 [7 7 1]] 

array3 * array3: 
 [[49  4 49]
 [49 49  1]] 

1 / array3: 
 [[0.14 0.5  0.14]
 [0.14 0.14 1.  ]] 

array3**0.5: 
 [[2.6 1.4 2.6]
 [2.6 2.6 1. ]] 

