In [1]:
import numpy as np

In [ ]:
# arrays with random numbers
arr1 = np.random.randn(4, 2)
arr2 = np.random.randint(1, 10, (4, 2))
print('array1:\n', arr1)
print('array2:\n', arr2)

In [ ]:
# element wise operations between arrays are those which are performed on each
# element of the array
# arithmetic operations with scalars are also element wise
sum_arrs = arr1 + arr2
print('sum of arrays:\n', sum_arrs)
one_divided_by_arr1 = 1 / arr1
print('1 / array1:\n', one_divided_by_arr1)

In [4]:
# 2x3 matrix
matrix1 = np.arange(1, 13).reshape(3, 4)
print('matrix1:\n', matrix1)

matrix1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# array creation
data1 = np.arange(1, 50+1)
print(data1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [22]:
# assign value to a slice of an array
data1[:25] = 0
print(data1)

sliced_data1 = data1[5:15]
print('Take a slice of data1:\n', sliced_data1)

# assign values to the sliced array
sliced_data1[[5]] = 12345
print(data1)
# this concludes that the sliced array is a view of the original array
# for creating a copy of the array use the copy() method

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Take a slice of data1:
 [0 0 0 0 0 0 0 0 0 0]
[    0     0     0     0     0     0     0     0     0     0 12345     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0    26    27    28    29    30    31    32    33    34    35    36
    37    38    39    40    41    42    43    44    45    46    47    48
    49    50]


In [27]:
# 2d array
data2 = np.arange(1, 25+1).reshape(5, 5)
print(data2)

#indexing a 2d array
print('data2[2,3]:\n', data2[2,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
data2[2,3]:
 14


In [30]:
# copy method
sliced_row = data2.copy()[2]
print('sliced_row\n', sliced_row)

sliced_row
 [11 12 13 14 15]


In [33]:
# boolean indexing 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print('names:\n', names)
print('data:\n', data)
names == 'Bob'
print('names == Bob:\n', names == 'Bob')

# here the boolean array is used to index the data array
data[names == 'Bob']

names:
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data:
 [[ 2.94074026 -0.78621902  2.2574019  -0.20450191]
 [ 0.77909049 -1.21593317  1.02586262 -2.04329893]
 [-0.66222524  0.75841947 -2.09331401 -0.3943492 ]
 [ 0.91745511  1.04764528  1.70087404 -0.53308791]
 [ 0.69518284 -0.55250381 -2.09616322 -0.01167602]
 [ 0.55223277 -1.51403148  0.54168921  0.46898503]
 [-0.66667886  0.27962946 -0.6241961  -0.49427111]]
names == Bob:
 [ True False False  True False False False]


array([[ 2.94074026, -0.78621902,  2.2574019 , -0.20450191],
       [ 0.91745511,  1.04764528,  1.70087404, -0.53308791]])