In [1]:
import numpy as np

In [3]:
# arrays with random numbers
arr1 = np.random.randn(4, 2).round(3)
arr2 = np.random.randint(1, 10, (4, 2))
print('array1:\n', arr1)
print('array2:\n', arr2)

array1:
 [[ 0.035  1.528]
 [-0.521  0.799]
 [-0.51   0.706]
 [-1.553  0.294]]
array2:
 [[4 3]
 [5 2]
 [2 8]
 [4 8]]


In [5]:
# element wise operations between arrays are those which are
# performed on each element of the array
# arithmetic operations with scalars are also element wise
sum_arrs = arr1 + arr2
print('sum of arrays:\n', sum_arrs)
one_divided_by_arr1 = (1 / arr1).round(2)
print('1 / array1:\n', one_divided_by_arr1)

sum of arrays:
 [[4.035 4.528]
 [4.479 2.799]
 [1.49  8.706]
 [2.447 8.294]]
1 / array1:
 [[28.57  0.65]
 [-1.92  1.25]
 [-1.96  1.42]
 [-0.64  3.4 ]]


In [6]:
# 3x4 matrix
matrix1 = np.arange(1, 13).reshape(3, 4)
print('matrix1:\n', matrix1)

matrix1:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
# array creation
data1 = np.arange(1, 50+1)
print(data1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [10]:
# assign value to a slice of an array
data1[:25] = 0
sliced_data1 = data1[5:15]

print(data1)
print('Take a slice of data1:\n', sliced_data1)

# assign values to the sliced array
sliced_data1[[5]] = 12345
print(data1)
# this concludes that the sliced array is a view of the original array
# for creating a copy of the array use the copy() method

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Take a slice of data1:
 [0 0 0 0 0 0 0 0 0 0]
[    0     0     0     0     0     0     0     0     0     0 12345     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0    26    27    28    29    30    31    32    33    34    35    36
    37    38    39    40    41    42    43    44    45    46    47    48
    49    50]


In [12]:
# 2d array
data2 = np.arange(1, 25+1).reshape(5, 5)
print(data2, '\n')

#indexing a 2d array
print('data2[2,3]:\n', data2[2,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

data2[2,3]:
 14


In [13]:
# copy method
sliced_row = data2.copy()[2]
print('sliced_row\n', sliced_row)

sliced_row
 [11 12 13 14 15]
