In [1]:
import numpy as np

In [2]:
# create a 8x8 matrix with random integers from -100 to 100 
matrix1 = np.random.randint(-10, 10+1, size=(8, 8))
matrix1

array([[ -1,   0,   5,   2,   9,  -1,   6,  -7],
       [  8,  -7,   4,  -6,  -1,   8,  -6, -10],
       [ -2,  -2,   9,  -3,  -9,  -8, -10,  -6],
       [ -9,  10,   1,   1,   2,   9,   9,   9],
       [ -7,  10,   9,   9,  -6,  -2,  -3,  -5],
       [  4,  10,  -6,   1,   2,  -8,  -5,  -2],
       [ -2,  -7,   5,  -6,  -7,  -1,   5,   6],
       [  9,  -7,   0,   8,   2,   3,   4,  -8]])

In [3]:
# bool matrix with bools > -25
greater_than_5_num = matrix1 > 5
print(greater_than_5_num)

[[False False False False  True False  True False]
 [ True False False False False  True False False]
 [False False  True False False False False False]
 [False  True False False False  True  True  True]
 [False  True  True  True False False False False]
 [False  True False False False False False False]
 [False False False False False False False  True]
 [ True False False  True False False False False]]


In [4]:
# opperatig with matrix elements
matrix1_product = matrix1 * -0.333
print(matrix1_product)

[[ 0.333 -0.    -1.665 -0.666 -2.997  0.333 -1.998  2.331]
 [-2.664  2.331 -1.332  1.998  0.333 -2.664  1.998  3.33 ]
 [ 0.666  0.666 -2.997  0.999  2.997  2.664  3.33   1.998]
 [ 2.997 -3.33  -0.333 -0.333 -0.666 -2.997 -2.997 -2.997]
 [ 2.331 -3.33  -2.997 -2.997  1.998  0.666  0.999  1.665]
 [-1.332 -3.33   1.998 -0.333 -0.666  2.664  1.665  0.666]
 [ 0.666  2.331 -1.665  1.998  2.331  0.333 -1.665 -1.998]
 [-2.997  2.331 -0.    -2.664 -0.666 -0.999 -1.332  2.664]]


In [5]:
# opperation between matrices
matrix2 = matrix1 + matrix1_product
print(matrix2)

[[-0.667  0.     3.335  1.334  6.003 -0.667  4.002 -4.669]
 [ 5.336 -4.669  2.668 -4.002 -0.667  5.336 -4.002 -6.67 ]
 [-1.334 -1.334  6.003 -2.001 -6.003 -5.336 -6.67  -4.002]
 [-6.003  6.67   0.667  0.667  1.334  6.003  6.003  6.003]
 [-4.669  6.67   6.003  6.003 -4.002 -1.334 -2.001 -3.335]
 [ 2.668  6.67  -4.002  0.667  1.334 -5.336 -3.335 -1.334]
 [-1.334 -4.669  3.335 -4.002 -4.669 -0.667  3.335  4.002]
 [ 6.003 -4.669  0.     5.336  1.334  2.001  2.668 -5.336]]


In [8]:
# sorted matrix axis 1
sorted_matrix = np.sort(matrix2, axis=1)
print('sort axis=1: \n',sorted_matrix)
# sorted matrix axis 0
sorted_matrix_zero_axis = np.sort(matrix2, axis=0)
print('sort arix=0 \n',sorted_matrix_zero_axis)

sort axis=1: 
 [[-4.669 -0.667 -0.667  0.     1.334  3.335  4.002  6.003]
 [-6.67  -4.669 -4.002 -4.002 -0.667  2.668  5.336  5.336]
 [-6.67  -6.003 -5.336 -4.002 -2.001 -1.334 -1.334  6.003]
 [-6.003  0.667  0.667  1.334  6.003  6.003  6.003  6.67 ]
 [-4.669 -4.002 -3.335 -2.001 -1.334  6.003  6.003  6.67 ]
 [-5.336 -4.002 -3.335 -1.334  0.667  1.334  2.668  6.67 ]
 [-4.669 -4.669 -4.002 -1.334 -0.667  3.335  3.335  4.002]
 [-5.336 -4.669  0.     1.334  2.001  2.668  5.336  6.003]]
sort arix=0 
 [[-6.003 -4.669 -4.002 -4.002 -6.003 -5.336 -6.67  -6.67 ]
 [-4.669 -4.669  0.    -4.002 -4.669 -5.336 -4.002 -5.336]
 [-1.334 -4.669  0.667 -2.001 -4.002 -1.334 -3.335 -4.669]
 [-1.334 -1.334  2.668  0.667 -0.667 -0.667 -2.001 -4.002]
 [-0.667  0.     3.335  0.667  1.334 -0.667  2.668 -3.335]
 [ 2.668  6.67   3.335  1.334  1.334  2.001  3.335 -1.334]
 [ 5.336  6.67   6.003  5.336  1.334  5.336  4.002  4.002]
 [ 6.003  6.67   6.003  6.003  6.003  6.003  6.003  6.003]]


In [3]:
# randn() method productes numbers sampled from a standard normal distribution
# Theoretically: No minimum or maximum limit.
# Practically: The range of values is unbounded, but values further
# away from 0 become increasingly rare.
data = np.random.randn(2,3)
print(data)

[[-1.01137134 -0.182087   -0.15953201]
 [ 0.2795801  -1.77559215 -0.07206091]]


In [4]:
# multiply data by 1.618
data_product = data * 1.618
print(data_product)

[[-1.63639882 -0.29461677 -0.25812279]
 [ 0.45236061 -2.8729081  -0.11659456]]


In [5]:
# get the shape of the ndim arra
print(data.shape)


(2, 3)

In [6]:
# product
arr3 = np.random.randint(1,10,(2,3))
print('array: \n',arr3,'\n')
print('array * array: \n', arr3 * arr3,'\n')
print('1 / array: \n', 1 / arr3,'\n')
print('array**0.5: \n', arr3**0.5,'\n')

array: 
 [[2 1 8]
 [3 3 2]] 

array * array: 
 [[ 4  1 64]
 [ 9  9  4]] 

1 / array: 
 [[0.5        1.         0.125     ]
 [0.33333333 0.33333333 0.5       ]] 

array**0.5: 
 [[1.41421356 1.         2.82842712]
 [1.73205081 1.73205081 1.41421356]] 

