In [1]:
import numpy as np

In [15]:
# boolean indexing 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4).round(2)
print('names = \n', names, '\n', 'data= \n', data)

names = 
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 
 data= 
 [[ 0.07  1.88 -0.34 -0.72]
 [ 0.46  1.13  0.57  0.27]
 [ 0.08  0.42  0.03  0.24]
 [ 1.1  -1.11 -0.07 -1.29]
 [ 0.93  0.88 -1.05  1.38]
 [-1.76 -1.76 -0.79  0.16]
 [-0.67  0.15  1.04  1.3 ]]


In [16]:
# we search for the Bob str in the 'names' array by comparison operator
# This method slices the row from the array according to boolean values
print('name == Bob: \n', names == 'Bob','\n')
print(data[names == 'Bob'],'\n') # print the equivalent of the rows assigned to Bob
print(data[names == 'Joe'],'\n') # print the equivalent of the rows assigned to Joe

name == Bob: 
 [ True False False  True False False False] 

[[ 0.07  1.88 -0.34 -0.72]
 [ 1.1  -1.11 -0.07 -1.29]] 

[[ 0.46  1.13  0.57  0.27]
 [-1.76 -1.76 -0.79  0.16]
 [-0.67  0.15  1.04  1.3 ]] 



In [17]:
# after slicing the rows, we can index the columns too
print('Will[2:]: \n',data[names == 'Will', 2:])
print('Joe[0]: \n',data[names == 'Joe',0])

Will[2:]: 
 [[ 0.03  0.24]
 [-1.05  1.38]]
Joe[0]: 
 [ 0.46 -1.76 -0.67]


In [20]:
# negation slicing
print('names != Bob: \n', names != 'Bob')
print(data[names != 'Bob',2])


names != Bob: 
 [False  True  True False  True  True  True]
[ 0.57  0.03 -1.05 -0.79  1.04]
