In [1]:
import numpy as np

In [2]:
# boolean indexing 
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)
print('names = \n', names, 'data= \n', data)

names = 
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] data= 
 [[ 0.05340302 -0.53332735  0.56814817 -0.17169178]
 [-0.28168294  0.72427286 -0.64461259 -0.72497635]
 [ 0.05354248 -1.48423265 -0.20877539 -0.08716222]
 [-0.4890187   0.35772428  0.43531618  1.64196174]
 [ 0.4793326  -2.14602865  0.04427534 -0.91041713]
 [ 0.84534265  0.47832384  1.56975589  2.07362993]
 [-1.16837936 -1.55611784  0.46159436 -1.46204934]]


In [3]:
# we search for the Bob str in the names array by comparison operator
# This method slices the row from the array according to boolean values
print('name == Bob: ', names == 'Bob')
print(data[names == 'Bob']) # print the equivalent of the rows assigned to Bob
print(data[names == 'Joe']) # print the equivalent of the rows assigned to Joe

name == Bob:  [ True False False  True False False False]
[[ 0.05340302 -0.53332735  0.56814817 -0.17169178]
 [-0.4890187   0.35772428  0.43531618  1.64196174]]
[[-0.28168294  0.72427286 -0.64461259 -0.72497635]
 [ 0.84534265  0.47832384  1.56975589  2.07362993]
 [-1.16837936 -1.55611784  0.46159436 -1.46204934]]


In [8]:
# after slicing the rows, we can index the columns too
print('Will[2:]: \n',data[names == 'Will', 2:])
print('Joe[0]: \n',data[names == 'Joe',0])

Will[2:]: 
 [[-0.20877539 -0.08716222]
 [ 0.04427534 -0.91041713]]
Joe[0]: 
 [-0.28168294  0.84534265 -1.16837936]


In [10]:
# negation slicing
print('names != Bob: \n', names != 'Bob')
print(data[names != 'Bob'])


names != Bob: 
 [False  True  True False  True  True  True]
[[-0.28168294  0.72427286 -0.64461259 -0.72497635]
 [ 0.05354248 -1.48423265 -0.20877539 -0.08716222]
 [ 0.4793326  -2.14602865  0.04427534 -0.91041713]
 [ 0.84534265  0.47832384  1.56975589  2.07362993]
 [-1.16837936 -1.55611784  0.46159436 -1.46204934]]
