In [2]:
import numpy as np

In [4]:
# matrix creation

matrix1 = np.linspace(1, 10, 100, dtype=float).reshape(10, 10).round(1)
print('matrix1: \n', matrix1)

matrix1: 
 [[ 1.   1.1  1.2  1.3  1.4  1.5  1.5  1.6  1.7  1.8]
 [ 1.9  2.   2.1  2.2  2.3  2.4  2.5  2.5  2.6  2.7]
 [ 2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.5  3.6]
 [ 3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.5]
 [ 4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5]
 [ 5.5  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4]
 [ 6.5  6.5  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3]
 [ 7.4  7.5  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2]
 [ 8.3  8.4  8.5  8.5  8.6  8.7  8.8  8.9  9.   9.1]
 [ 9.2  9.3  9.4  9.5  9.5  9.6  9.7  9.8  9.9 10. ]]


In [5]:
# print bool matrix with condition
bool_matrix = matrix1 > 5
bool_matrix

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [6]:
# conditions doesnt change the original matrix
matrix1

array([[ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.5,  1.6,  1.7,  1.8],
       [ 1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.5,  2.6,  2.7],
       [ 2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.5,  3.6],
       [ 3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.5],
       [ 4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5],
       [ 5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4],
       [ 6.5,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3],
       [ 7.4,  7.5,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2],
       [ 8.3,  8.4,  8.5,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,  9.1],
       [ 9.2,  9.3,  9.4,  9.5,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ]])

In [8]:
bool_matrix_and = (matrix1 > 2) & (matrix1 < 8)
bool_matrix_and

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [9]:
arr2 = np.random.randint(-10, 10, size=(10,10))
arr2

array([[ -6,   2, -10,  -2,   6,   6,   4,   8,  -7,   4],
       [ -6,   0,  -3,   4,   1,  -6,  -2,  -4,   2,  -6],
       [  2,   6,   2, -10,  -4,  -4,   8,   6,   9,   6],
       [ -3,  -4,  -6, -10,   6,  -5,  -6,   5,   5,  -9],
       [ -6,  -7,  -3,   1,  -5,  -8, -10,  -2,   2, -10],
       [ -1,   0,  -3,   8,  -1,   0,   4,  -2, -10,  -8],
       [ -9,  -4,   3,   4,   8,   0,   2,   3, -10,  -5],
       [-10,  -3,   1, -10,   6, -10,  -5,   1,  -3,   1],
       [  7,   8,   3,  -3,   8,   3,   3,   8,  -3,  -9],
       [  2,  -7,   4,   7,   1,  -4,   9,  -9, -10,   2]])

In [10]:
# catching if there are negaticve values
bool_neg_arr2 = arr2 < 0
print(bool_neg_arr2)

[[ True False  True  True False False False False  True False]
 [ True False  True False False  True  True  True False  True]
 [False False False  True  True  True False False False False]
 [ True  True  True  True False  True  True False False  True]
 [ True  True  True False  True  True  True  True False  True]
 [ True False  True False  True False False  True  True  True]
 [ True  True False False False False False False  True  True]
 [ True  True False  True False  True  True False  True False]
 [False False False  True False False False False  True  True]
 [False  True False False False  True False  True  True False]]


In [11]:
bool_neg_arr2[0:25]
bool_neg_arr2

array([[ True, False,  True,  True, False, False, False, False,  True,
        False],
       [ True, False,  True, False, False,  True,  True,  True, False,
         True],
       [False, False, False,  True,  True,  True, False, False, False,
        False],
       [ True,  True,  True,  True, False,  True,  True, False, False,
         True],
       [ True,  True,  True, False,  True,  True,  True,  True, False,
         True],
       [ True, False,  True, False,  True, False, False,  True,  True,
         True],
       [ True,  True, False, False, False, False, False, False,  True,
         True],
       [ True,  True, False,  True, False,  True,  True, False,  True,
        False],
       [False, False, False,  True, False, False, False, False,  True,
         True],
       [False,  True, False, False, False,  True, False,  True,  True,
        False]])

In [14]:
# division by zero
matrix2 = np.random.randint(-10, 10+1, size=(10,10))
print('matrix2: \n',matrix2)

# here we execute the opperation for the matrix elements
one_divided_matrix = (1 / matrix2).round(2)
print('1/matrix2: \n', one_divided_matrix)
# those values who are 1 / 0 are inf

matrix2: 
 [[  8   6  -4   9   2  -4   8  10   3  -9]
 [ -6 -10  -1   5  -5  -3   8   1  10  -5]
 [  9   9  -2   7   8   2   4  -8   3  -3]
 [  3  -7  -7  -6  -2  -2   6  -9  -4  -3]
 [  6  -8   9   8   9   9   3   0  -6  -7]
 [ -4 -10 -10   1  -4  -5  -4  -3   3   1]
 [ -7  -5  -4   3  -8   2   8   5   9  -9]
 [  6   3   0  -2   5  -6  -5  -9   5   3]
 [ -8  -4   9   6   9   8   7  -5   1  -4]
 [  2   6   7   4   4  10  -7  -8  -9  -3]]
1/matrix2: 
 [[ 0.12  0.17 -0.25  0.11  0.5  -0.25  0.12  0.1   0.33 -0.11]
 [-0.17 -0.1  -1.    0.2  -0.2  -0.33  0.12  1.    0.1  -0.2 ]
 [ 0.11  0.11 -0.5   0.14  0.12  0.5   0.25 -0.12  0.33 -0.33]
 [ 0.33 -0.14 -0.14 -0.17 -0.5  -0.5   0.17 -0.11 -0.25 -0.33]
 [ 0.17 -0.12  0.11  0.12  0.11  0.11  0.33   inf -0.17 -0.14]
 [-0.25 -0.1  -0.1   1.   -0.25 -0.2  -0.25 -0.33  0.33  1.  ]
 [-0.14 -0.2  -0.25  0.33 -0.12  0.5   0.12  0.2   0.11 -0.11]
 [ 0.17  0.33   inf -0.5   0.2  -0.17 -0.2  -0.11  0.2   0.33]
 [-0.12 -0.25  0.11  0.17  0.11  0.12  0.

C:\Users\damal\AppData\Local\Temp\ipykernel_4060\2252910985.py:6: RuntimeWarning: divide by zero encountered in divide
  one_divided_matrix = (1 / matrix2).round(2)
