In [1]:
import numpy as np

In [2]:
# sorting matrix elements

matrix = np.random.randint(-100, 100, size=(13, 10))
# print(matrix)
matrix.sort(axis=1)
# parameters: axis=1 for horizontal sorting, axis=2 for vertical sorting
print(matrix)

[[-80 -78 -54 -38  -9   2   7  50  80  94]
 [-90 -90 -71 -57 -18  -9  51  55  56  87]
 [-71 -68 -59 -38   0   9  15  25  64  75]
 [-96 -56 -48 -45 -33 -24 -20 -15  -6  83]
 [-96 -75 -63  -6  -3  24  61  67  94  96]
 [-84 -76 -62 -30 -27 -14 -13   2  76  85]
 [-68 -45 -32 -19 -16  44  68  73  73  92]
 [-70 -48 -44  11  39  46  51  71  90  99]
 [-98 -94 -83 -82 -80 -58  -4   6  39  88]
 [-92 -64 -61 -51 -49 -44  14  20  44  95]
 [-77 -44 -28 -14  -8  21  28  68  82  83]
 [-77 -72 -36 -22 -12 -11  -3  -2   2  37]
 [-91 -87 -83 -83 -39  22  26  63  72  91]]


In [5]:
# extract the percentiles
# in a sorted list, if 0 is initial value and 100 is final value
# percentiles are were the values are divided in 100 parts
percentiles = [0, 25, 50, 75, 100]

# percentile 50 is the median

In [8]:
# note: you must take into account that the percentile is a value, not
# a position in the list nor a value in the list (ITS POSSIBLE IT
# DOESN'T APPEAR ON THE LIST)
percentile_50_matrix_as_array = np.percentile(matrix, percentiles[2], axis=1)
print('Percentile 50: \n',percentile_50_matrix_as_array,'\nindex: \n')

Percentile 50: 
 [ 10.  -45.  -37.5 -10.  -21.   -8.   -1.  -13.5  35.5  -5.5  19.  -78.
  -7.5] 
index: 



In [10]:
for p in percentiles[2:4]:
    values = np.percentile(matrix, p, axis=1)
    print(f'percentile {p} is {values}')

percentile 50 is [ 10.  -45.  -37.5 -10.  -21.   -8.   -1.  -13.5  35.5  -5.5  19.  -78.
  -7.5]
percentile 75 is [ 21.   -35.75  30.    21.5   44.5   75.75  48.75  55.25  83.75  60.25
  25.5  -15.75  68.25]


In [11]:
arr1 = np.random.randint(1, 100, size=120)
arr1

array([74, 51, 96, 75, 26,  4, 83, 89, 46, 93, 77, 73, 40, 78, 63,  1, 53,
       23, 79, 16, 93,  9, 55, 39, 54, 21, 29, 39, 83, 10, 77,  8, 31, 41,
       77, 86, 51, 94, 10, 90,  7, 34, 34, 45, 37, 61, 25,  5, 73, 45,  3,
       59, 77, 65, 27, 91, 63, 69, 17, 24, 40, 78, 14, 97, 26, 77, 38, 36,
       99, 85, 65,  3, 96,  6, 49, 95, 15, 98, 63, 71, 98, 45, 66, 25,  9,
       92, 55, 50, 45, 16,  5, 71, 14, 24, 45, 89, 54,  8, 96, 94,  3,  9,
       28, 89, 73, 39, 19, 34, 13, 94, 37, 62, 17,  9, 52, 21,  5,  6, 67,
       59])

In [40]:
# std is the std deviation, sqrt of variance. Avg distance between each
# value and the mean
# mean is the average of the values
# median is the value in the middle of the values
st1 = np.std(arr1)
median1 = np.median(arr1)
average1 = np.mean(arr1)
variance1 = np.var(arr1)
print('Average: ', average1) 
print('Median: ', median1)
print('Std: ', st1)
print('Variance: ', variance1)

Average:  48.0
Median:  47.5
Std:  29.785063370756827
Variance:  887.15


In [6]:
#statistics
arr2 = np.random.randn(6,4)
print('original array: \n', arr2)
print('mean: ', arr2.mean())
print('sum: ', arr2.sum())

original array: 
 [[-0.77880313 -0.03151908  1.29721593 -0.09556712]
 [-0.54949588  0.84895931 -0.25533914 -1.82405139]
 [-0.30944111  1.55551549 -1.59469967  1.79884314]
 [-1.58576786 -1.07667957  0.24815972  0.19217402]
 [ 1.24919259 -0.09221629 -1.43840096  0.50109968]
 [ 0.12434079  1.2943004  -1.21820207 -0.68303413]]
mean:  -0.10097567961654073
sum:  -2.4234163107969775
