In [1]:
import numpy as np

In [4]:
# sorting matrix elements

matrix = np.random.randint(-100, 100, size=(13, 10))
# print(matrix)
matrix.sort(axis=1)
# parameters: axis=1 for horizontal sorting, axis=2 for vertical sorting
print(matrix)

[[ -46  -35   -1    4    5   15   18   22   24   26]
 [ -74  -59  -56  -53  -51  -39  -38  -35  -22   13]
 [ -84  -78  -77  -72  -39  -36   -3   41   73   85]
 [ -86  -73  -52  -17  -16   -4   20   22   60   86]
 [ -69  -65  -32  -30  -22  -20   43   45   61   74]
 [ -66  -58  -35  -21  -13   -3   45   86   91   93]
 [ -97  -73  -39  -28  -12   10   30   55   83   99]
 [ -31  -28  -21  -15  -14  -13   44   59   64   97]
 [ -77   -8   17   23   32   39   71   88   92   93]
 [ -98  -66  -45  -28  -24   13   16   75   79   81]
 [ -97  -67  -41   -3   15   23   24   26   66   77]
 [-100  -92  -90  -88  -80  -76  -57   -2    1   42]
 [ -90  -63  -26  -25  -23    8   66   69   73   99]]


In [5]:
# extract the percentiles
# in a sorted list, if 0 is initial value and 100 is final value
# percentiles are were the values are divided in 100 parts
percentiles = [0, 25, 50, 75, 100]

# percentile 50 is the median

In [8]:
# note: you must take into account that the percentile is a value, not
# a position in the list nor a value in the list (ITS POSSIBLE IT
# DOESN'T APPEAR ON THE LIST)
percentile_50_matrix_as_array = np.percentile(matrix, percentiles[2], axis=1)
print('Percentile 50: \n',percentile_50_matrix_as_array,'\nindex: \n')

Percentile 50: 
 [ 10.  -45.  -37.5 -10.  -21.   -8.   -1.  -13.5  35.5  -5.5  19.  -78.
  -7.5] 
index: 



In [10]:
for p in percentiles[2:4]:
    values = np.percentile(matrix, p, axis=1)
    print(f'percentile {p} is {values}')

percentile 50 is [ 10.  -45.  -37.5 -10.  -21.   -8.   -1.  -13.5  35.5  -5.5  19.  -78.
  -7.5]
percentile 75 is [ 21.   -35.75  30.    21.5   44.5   75.75  48.75  55.25  83.75  60.25
  25.5  -15.75  68.25]


In [11]:
arr1 = np.random.randint(1, 100, size=120)
arr1

array([74, 51, 96, 75, 26,  4, 83, 89, 46, 93, 77, 73, 40, 78, 63,  1, 53,
       23, 79, 16, 93,  9, 55, 39, 54, 21, 29, 39, 83, 10, 77,  8, 31, 41,
       77, 86, 51, 94, 10, 90,  7, 34, 34, 45, 37, 61, 25,  5, 73, 45,  3,
       59, 77, 65, 27, 91, 63, 69, 17, 24, 40, 78, 14, 97, 26, 77, 38, 36,
       99, 85, 65,  3, 96,  6, 49, 95, 15, 98, 63, 71, 98, 45, 66, 25,  9,
       92, 55, 50, 45, 16,  5, 71, 14, 24, 45, 89, 54,  8, 96, 94,  3,  9,
       28, 89, 73, 39, 19, 34, 13, 94, 37, 62, 17,  9, 52, 21,  5,  6, 67,
       59])

In [40]:
# std is the std deviation, sqrt of variance. Avg distance between each
# value and the mean
# mean is the average of the values
# median is the value in the middle of the values
st1 = np.std(arr1)
median1 = np.median(arr1)
average1 = np.mean(arr1)
variance1 = np.var(arr1)
print('Average: ', average1) 
print('Median: ', median1)
print('Std: ', st1)
print('Variance: ', variance1)

Average:  48.0
Median:  47.5
Std:  29.785063370756827
Variance:  887.15


In [6]:
#statistics
arr2 = np.random.randn(6,4)
print('original array: \n', arr2)
print('mean: ', arr2.mean())
print('sum: ', arr2.sum())

original array: 
 [[-0.77880313 -0.03151908  1.29721593 -0.09556712]
 [-0.54949588  0.84895931 -0.25533914 -1.82405139]
 [-0.30944111  1.55551549 -1.59469967  1.79884314]
 [-1.58576786 -1.07667957  0.24815972  0.19217402]
 [ 1.24919259 -0.09221629 -1.43840096  0.50109968]
 [ 0.12434079  1.2943004  -1.21820207 -0.68303413]]
mean:  -0.10097567961654073
sum:  -2.4234163107969775
