In [2]:
import numpy as np

In [4]:
arr1 = np.random.randint(1, 10, size=(30, 40))
arr1

array([[2, 5, 2, ..., 6, 9, 1],
       [7, 3, 7, ..., 2, 7, 9],
       [3, 2, 1, ..., 1, 9, 6],
       ...,
       [5, 6, 3, ..., 9, 1, 8],
       [2, 5, 9, ..., 5, 3, 1],
       [4, 2, 6, ..., 3, 8, 8]])

In [6]:
# maximum value of each row
np.max(arr1, axis=1) # axis=1 means row

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9])

In [20]:
nines_to_zeros = np.max(arr1, axis=0) # axis=0 means column
print(nines_to_zeros)
print(nines_to_zeros.shape, nines_to_zeros.ndim, nines_to_zeros.dtype)
# ERROR zeros = np.zeros(nines_to_zeros)

[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9
 9 9 9]
(40,) 1 int32


In [25]:
# matrix of random integers from -100 to 100

matrix = np.random.randint(-99,99+1, size=(8,13))
matrix

array([[ 77, -50, -32,  58, -37,  12, -89, -21, -69,  58, -85,  -3, -32],
       [ 55, -71,  39, -71,  87,  75, -15, -62, -31, -97,  77,  30,  87],
       [ 62, -65, -31,  29,  16,  50, -15, -16, -29,   3, -76,  32, -99],
       [-78,  77, -94,  78,  20,  54,  12,  -2,  45,  16,   3, -62,  77],
       [-19, -18,  38, -31,  35,   8, -79, -37, -48, -45, -23, -41,  -1],
       [ 70,  -6,  27, -12,   1, -30,  14, -61,  56, -94, -29,  38, -43],
       [-35, -12, -35,  23,  68, -78, -50,  75,  -7,  99, -90, -51,  58],
       [ 21, -67, -61, -63, -85, -31,  85, -91,  18,  62,  19, -21,  94]])

In [27]:
# maximum value of each row: axis=1, column: axis=0
max_values = np.max(matrix, axis=1)
max_values

array([77, 87, 62, 78, 38, 70, 99, 94])

In [30]:
# argmax of each row: axis=1, column: axis=0
args_max_values = np.argmax(matrix, axis=1)
args_max_values

array([ 0,  4,  0,  3,  2,  0,  9, 12], dtype=int64)

In [34]:
# argmin of each row: axis=1, column: axis=0
args_min_values = np.argmin(matrix, axis=1)
args_min_values


array([ 6,  9, 12,  2,  6,  9, 10,  7], dtype=int64)

In [35]:
# represents the difference between the maximum and minimum values of each
# row: axis=1, column: axis=0
matrix.ptp(axis=1) # peak to peak

array([166, 184, 161, 172, 117, 164, 189, 185])