In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1, 10, size=(30, 40))
arr1

array([[6, 2, 1, ..., 1, 3, 1],
       [4, 4, 1, ..., 9, 1, 7],
       [4, 5, 8, ..., 9, 2, 7],
       ...,
       [2, 3, 3, ..., 8, 6, 3],
       [7, 7, 5, ..., 8, 7, 6],
       [7, 6, 1, ..., 4, 6, 8]])

In [3]:
# maximum value of each row
np.max(arr1, axis=1) # axis=1 means row

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9])

In [4]:
nines_to_zeros = np.max(arr1, axis=0) # axis=0 means column
print(nines_to_zeros)
print(nines_to_zeros.shape, nines_to_zeros.ndim, nines_to_zeros.dtype)
# ERROR zeros = np.zeros(nines_to_zeros)

[9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9
 9 9 9]
(40,) 1 int32


In [5]:
# matrix of random integers from -100 to 100

matrix = np.random.randint(-99,99+1, size=(8,13))
matrix

array([[-32,  11,  46,  35, -33, -49,  35,  35,  75, -62,  -3,  55,  32],
       [ 86,  -7, -72, -18,  31,  88,  92,  34, -39,  21,  54,  98,  14],
       [  8,  97, -67,  19, -58,  15,  96,  18,  49,  -6,  94,  90,  59],
       [-51,  -6,  89,  72,  70, -69, -41,  68, -32, -64, -45, -45,  94],
       [ 99,  90, -34, -84, -17, -55,  20,  50, -56,  52,  31, -27, -93],
       [ 19, -35, -33,  -6,  22, -21, -83,  88,  -8,  82, -91, -34, -24],
       [ 16,   6,  43,  77, -10, -50, -91,  74, -90, -39,  14,  93, -35],
       [-71, -73, -36,  70,  18,  48,  20, -28, -20, -65,  73,  52,  13]])

In [6]:
# maximum value of each row: axis=1, column: axis=0
max_values = np.max(matrix, axis=1)
max_values

array([75, 98, 97, 94, 99, 88, 93, 73])

In [7]:
# argmax of each row: axis=1, column: axis=0. It prints the index
# of the max values for each row(axis=1).
args_max_values = np.argmax(matrix, axis=1)
args_max_values

array([ 8, 11,  1, 12,  0,  7, 11, 10], dtype=int64)

In [8]:
# argmin of each row: axis=1, column: axis=0.  It prints the index
# of the mn values for each column(axis=0).
args_min_values = np.argmin(matrix, axis=0)
args_min_values


array([7, 7, 1, 4, 2, 3, 6, 7, 6, 7, 5, 3, 4], dtype=int64)

In [9]:
# represents the difference between the maximum and minimum values
# of each row: axis=1, column: axis=0
matrix.ptp(axis=1) # peak to peak

array([137, 170, 164, 163, 192, 179, 184, 146])