In [1]:
import numpy as np

In [6]:
# ndarray is a n dimensional array object, fast and flexible
# container for large datasets in python
# generate some rdm data
data = np.random.randn(8, 5)
data_type = data.dtype
print(data, data_type, data.shape)
data2 = np.random.randn(3,2)
print(data2, data2.dtype, data2.shape)

[[-0.1909479   0.63776803 -2.42010049  0.16655948  0.02072981]
 [-0.95119364 -1.36396973 -0.21593527  1.05068609 -0.63993395]
 [ 0.49640745  1.21329591 -0.1915422   1.33464629 -0.37118066]
 [ 0.87950461 -0.0130963   0.1784559  -0.62371472  0.26541447]
 [ 0.4817146   1.06246978 -0.05892718 -0.7048289  -0.54905996]
 [-1.51345803  0.8220963   0.19313728 -0.42726031 -0.43141357]
 [-1.52621739  2.0220447  -0.9954815   1.00254231  0.65450816]
 [-0.53020825  0.40498578  0.75622301  0.21568335  0.47399738]] float64 (8, 5)
[[ 0.06534598  0.60230353]
 [ 0.63070577  0.57826842]
 [ 2.24640111 -1.52470739]] float64 (3, 2)


In [3]:
# aggregation functions
# sum by axis
sum_data_rows = np.sum(data, axis=1)
sum_data_columns =np.sum(data, axis=0)
print('The sum of rows is: ', sum_data_rows, '\nThe sum of columns is: ', sum_data_columns)

The sum of rows is:  [ 2.35880932  1.18719856 -4.78025249  4.41551822  0.17541308 -1.01003226
 -0.22943677  0.30418702] 
The sum of columns is:  [ 3.07273547 -1.45225823 -0.45312943 -3.37094866  4.62500553]


In [4]:
# array attributes

print('The shape of data is: ', data.shape, '\nThe dimension of data is: ', data.ndim, '\nThe data type of data is: ', data.dtype, '\nThe size of data is: ', data.size)	

The shape of data is:  (8, 5) 
The dimension of data is:  2 
The data type of data is:  float64 
The size of data is:  40
