In [1]:
import numpy as np

In [6]:
# ndarray is a n dimensional array object, fast and flexible
# container for large datasets in python
# generate some rdm data
data = np.random.randn(8, 5)
data_type = data.dtype
print('array: \n',data,'\n\narray type: \n', data_type,'\nsize: \n',data.shape)
data2 = np.random.randn(3,2)
print('\n\narray2: \n',data2,'\n\narray type: \n', data2.dtype,'\nsize: \n',data2.shape)

array: 
 [[-1.2353531  -0.38334531 -0.19963111  0.16017715  0.53654187]
 [-0.5130171  -0.3130553  -0.76915387  0.37502454  0.62476159]
 [ 0.07854793 -0.44554422 -0.27745722 -1.27715497  0.61020257]
 [ 1.19991048 -0.20386101  1.67934977 -1.10157456  1.90232885]
 [ 1.89886244 -1.57927794 -0.6935962  -0.43197362 -0.23613251]
 [-1.38412373 -1.04977399  1.76944048 -1.02137459  0.23533004]
 [ 0.32058203 -0.12281949  0.2760281  -1.39022398 -1.06719918]
 [-1.14036259  0.84476537  0.12564717 -0.23890099  1.07856402]] 

array type: 
 float64 
size: 
 (8, 5)


array2: 
 [[-0.2156159  -0.20920652]
 [ 0.52715161  0.80050909]
 [ 1.98264698 -1.63234938]] 

array type: 
 float64 
size: 
 (3, 2)


In [7]:
# aggregation functions
# sum by axis
sum_data_rows = np.sum(data, axis=1)
sum_data_columns =np.sum(data, axis=0)
print('The sum of rows is: ', sum_data_rows, '\nThe sum of columns is: ', sum_data_columns)

The sum of rows is:  [-1.12161051 -0.59544014 -1.31140591  3.47615354 -1.04211782 -1.45050179
 -1.98363252  0.66971298] 
The sum of columns is:  [-0.77495363 -3.25291189  1.91062711 -4.92600101  3.68439725]


In [8]:
# array attributes

print('The shape of data is: ', data.shape, '\nThe dimension of data is: ', data.ndim, '\nThe data type of data is: ', data.dtype, '\nThe size of data is: ', data.size)	

The shape of data is:  (8, 5) 
The dimension of data is:  2 
The data type of data is:  float64 
The size of data is:  40
