In [2]:
#import numpy library
import numpy as np

In [3]:
arr1 = np.random.randint(1, 100, (9,10))
arr2 = np.random.randn(6,4)
print('arr1: \n', arr1,'\nndim: ',arr1.ndim,'\narr2: \n', arr2,'\nndim: ', arr2.ndim)

arr1: 
 [[85 57 47 50 97  9 82 97 89 71]
 [33 77 14 29 94 25 61 49 16 30]
 [93 29 28 99  7 24 53 45 42 74]
 [90 61 50 77 80 14 74 73 29 44]
 [77 69 95 35 51 85 29 75 25  4]
 [86 85 88 20 15 50 16 13 98 42]
 [78 81 27 13 58 59 46 71 79 86]
 [11 96 86 28  4 76 72 18 90 40]
 [38 21  3 32  4  2 89 10 89  1]] 
ndim:  2 
arr2: 
 [[ 0.18934227  1.96256899 -0.45798059  1.85059774]
 [-0.49631822  0.56718464  0.86398715 -1.36362963]
 [ 0.17911132 -1.98010717 -2.18958085  1.58744499]
 [ 0.16477756  1.0177006  -1.42781727 -0.38135097]
 [-0.62115848 -0.06356    -1.30743271 -0.26578738]
 [-1.07981723  0.25779363  1.00872652  1.28046638]] 
ndim:  2


In [4]:
# .shape is a tuple that gives dimensions of the array
arr1.shape

(9, 10)

In [5]:
# .ndim gives the number of dimensions of the array
arr1.ndim

2

In [6]:
# .reshape reshapes the array
# 90 = 2 * 3 * 3 * 5
arr1.reshape(6,15)

array([[85, 57, 47, 50, 97,  9, 82, 97, 89, 71, 33, 77, 14, 29, 94],
       [25, 61, 49, 16, 30, 93, 29, 28, 99,  7, 24, 53, 45, 42, 74],
       [90, 61, 50, 77, 80, 14, 74, 73, 29, 44, 77, 69, 95, 35, 51],
       [85, 29, 75, 25,  4, 86, 85, 88, 20, 15, 50, 16, 13, 98, 42],
       [78, 81, 27, 13, 58, 59, 46, 71, 79, 86, 11, 96, 86, 28,  4],
       [76, 72, 18, 90, 40, 38, 21,  3, 32,  4,  2, 89, 10, 89,  1]])

In [7]:
# we can reshape the array to a higher dimension tensor
arr1.reshape(3,2,3,5)

array([[[[85, 57, 47, 50, 97],
         [ 9, 82, 97, 89, 71],
         [33, 77, 14, 29, 94]],

        [[25, 61, 49, 16, 30],
         [93, 29, 28, 99,  7],
         [24, 53, 45, 42, 74]]],


       [[[90, 61, 50, 77, 80],
         [14, 74, 73, 29, 44],
         [77, 69, 95, 35, 51]],

        [[85, 29, 75, 25,  4],
         [86, 85, 88, 20, 15],
         [50, 16, 13, 98, 42]]],


       [[[78, 81, 27, 13, 58],
         [59, 46, 71, 79, 86],
         [11, 96, 86, 28,  4]],

        [[76, 72, 18, 90, 40],
         [38, 21,  3, 32,  4],
         [ 2, 89, 10, 89,  1]]]])

In [ ]:
# by default, reshape() uses C-style ordering
# error occurs if the new shape does not match the original shape