In [1]:
#import numpy library
import numpy as np

In [11]:
arr1 = np.random.randint(1, 100, (9,10))
arr2 = np.random.randn(6,4)
print('arr1: \n', arr1,'\nndim: ',arr1.ndim,'\narr2: \n', arr2,'\nndim: ', arr2.ndim)

arr1: 
 [[38 14 57 52 83 20 96 72 80 62]
 [30 12 44 35 22 14 21 99 63 11]
 [27 23 71 49 32  3 89 28 27 98]
 [83 60 16 76 20 18 63  8 46 55]
 [72 52 62 32  3 20 58 64 65 66]
 [71 50 90 60 69 57 40 88 58 18]
 [14 53 43 27 67 68 73 16 47 93]
 [ 6 97 86 84 84  6 63 29 99 21]
 [68  1 91 23 40 95 30 64 33 97]] 
ndim:  2 
arr2: 
 [[-0.1332587  -0.13109445 -0.33300916 -0.50287944]
 [-0.40230627 -1.50515991  0.56316568  1.98517036]
 [-1.87696299  0.22304486 -2.16144252 -1.09472676]
 [ 0.10997847  0.81181389  0.38744767  0.26789095]
 [-0.01466707  0.53236595 -0.60917547 -0.36186811]
 [ 0.39783819 -1.14736061 -0.06393406 -1.21360725]] 
ndim:  2


In [3]:
# .shape is a tuple that gives dimensions of the array
arr1.shape

(9, 10)

In [ ]:
# .ndim gives the number of dimensions of the array
arr1.ndim

In [ ]:
# .reshape reshapes the array
# 90 = 2 * 3 * 3 * 5
arr1.reshape(6,15)

In [ ]:
# we can reshape the array to a higher dimension tensor
arr1.reshape(3,2,3,5)

In [ ]:
# by default, reshape() uses C-style ordering
# error occurs if the new shape does not match the original shape