In [2]:
import numpy as np

In [2]:
medellin_temps_celsius1 = np.random.randint(15,30+1,size=360)
medellin_temps_celsius1

array([15, 25, 17, 18, 30, 19, 25, 27, 26, 26, 25, 17, 15, 20, 25, 30, 20,
       16, 29, 24, 21, 21, 15, 26, 19, 25, 26, 29, 27, 19, 19, 22, 29, 22,
       19, 26, 16, 26, 19, 20, 27, 22, 17, 16, 20, 17, 18, 27, 29, 20, 26,
       21, 18, 27, 17, 26, 29, 20, 26, 21, 21, 21, 26, 25, 20, 30, 28, 20,
       23, 17, 18, 30, 23, 25, 17, 15, 15, 26, 23, 29, 16, 15, 17, 17, 24,
       27, 28, 18, 18, 19, 20, 22, 21, 23, 24, 15, 19, 22, 23, 28, 16, 20,
       28, 17, 16, 26, 17, 22, 21, 16, 25, 21, 20, 16, 27, 20, 28, 30, 29,
       18, 30, 22, 17, 30, 24, 18, 19, 30, 19, 21, 21, 29, 17, 17, 29, 29,
       23, 27, 29, 30, 24, 24, 18, 17, 25, 25, 28, 30, 30, 15, 21, 19, 29,
       18, 22, 23, 29, 21, 23, 17, 27, 22, 17, 28, 17, 22, 29, 30, 20, 19,
       15, 20, 28, 22, 18, 25, 16, 24, 30, 19, 22, 26, 17, 27, 25, 15, 22,
       24, 27, 17, 18, 18, 17, 15, 22, 18, 27, 25, 19, 21, 28, 17, 24, 22,
       17, 18, 26, 15, 28, 20, 16, 27, 30, 23, 23, 28, 27, 25, 26, 18, 16,
       17, 30, 25, 29, 28

In [3]:
mean_mde1 = np.mean(medellin_temps_celsius1)
median_mde1 = np.median(medellin_temps_celsius1)
print("Mean: ", mean_mde1," Median: ", median_mde1)

Mean:  22.25  Median:  22.0


In [4]:
(temperature_celcius, number_of_days) = np.unique(medellin_temps_celsius1, return_counts=True)
print("celcius_temp: ",temperature_celcius)
print( "number_of_days",number_of_days)

celcius_temp:  [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
number_of_days [24 22 30 26 22 22 22 23 16 18 26 24 22 23 18 22]


In [5]:
temp_cel_reshape = np.reshape(medellin_temps_celsius1, (5,72))
temp_cel_reshape # from here i want to create 3d arrays

array([[15, 25, 17, 18, 30, 19, 25, 27, 26, 26, 25, 17, 15, 20, 25, 30,
        20, 16, 29, 24, 21, 21, 15, 26, 19, 25, 26, 29, 27, 19, 19, 22,
        29, 22, 19, 26, 16, 26, 19, 20, 27, 22, 17, 16, 20, 17, 18, 27,
        29, 20, 26, 21, 18, 27, 17, 26, 29, 20, 26, 21, 21, 21, 26, 25,
        20, 30, 28, 20, 23, 17, 18, 30],
       [23, 25, 17, 15, 15, 26, 23, 29, 16, 15, 17, 17, 24, 27, 28, 18,
        18, 19, 20, 22, 21, 23, 24, 15, 19, 22, 23, 28, 16, 20, 28, 17,
        16, 26, 17, 22, 21, 16, 25, 21, 20, 16, 27, 20, 28, 30, 29, 18,
        30, 22, 17, 30, 24, 18, 19, 30, 19, 21, 21, 29, 17, 17, 29, 29,
        23, 27, 29, 30, 24, 24, 18, 17],
       [25, 25, 28, 30, 30, 15, 21, 19, 29, 18, 22, 23, 29, 21, 23, 17,
        27, 22, 17, 28, 17, 22, 29, 30, 20, 19, 15, 20, 28, 22, 18, 25,
        16, 24, 30, 19, 22, 26, 17, 27, 25, 15, 22, 24, 27, 17, 18, 18,
        17, 15, 22, 18, 27, 25, 19, 21, 28, 17, 24, 22, 17, 18, 26, 15,
        28, 20, 16, 27, 30, 23, 23, 28],
       [27, 2

In [6]:
# 1. create a matrix of zeros 3d
matrix3_d_zeros = np.zeros((3,3,3))
matrix3_d_zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
# 2. create a 3d matrix of 1s
matrix_3d_one = np.ones((3,3,3))
matrix_3d_one

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [3]:
# 3. array creation

arr1 = np.random.randint(-100,100+1,size=100)
arr1

array([  -8,   -9,  -70,   62,  -85,   38,   67,  -66,  -16,   40,   37,
         99,  -82,  -70,  -97,    0,   26,  -93,   33,   49,   92,  -45,
         96,   59,   29,  -72,   86,  -63,   82,   56,   70,    1,   -7,
         51,  -78,   -3,   23, -100,   25,    5,  -84,  -67,  -90,    5,
         50,  -41,    8,  -55,  -92,   20,   49,   42,   29,   99,   26,
         80,   85,  -31,   24,  -48,  -80,  -36,  -81,   13,  -43,   69,
        -22,  -67,   65,   57,   13,   63,  -19,   -5,  -43,   44,   88,
        -51,   84,   17,  -69,  -68,   75,   32,   61,    4,   41,   69,
         31,   94,   41,  100,   12,   91,  -85,   33,  -25,   76,   58,
        -58])

In [5]:
# np.shape() is used to determine the shape of the array
shape = np.shape(arr1)
shape

(100,)

In [6]:
# np.reshape() is used to reshape the array
arr_reshaped = np.reshape(arr1,(4,25))
arr_reshaped 

array([[  -8,   -9,  -70,   62,  -85,   38,   67,  -66,  -16,   40,   37,
          99,  -82,  -70,  -97,    0,   26,  -93,   33,   49,   92,  -45,
          96,   59,   29],
       [ -72,   86,  -63,   82,   56,   70,    1,   -7,   51,  -78,   -3,
          23, -100,   25,    5,  -84,  -67,  -90,    5,   50,  -41,    8,
         -55,  -92,   20],
       [  49,   42,   29,   99,   26,   80,   85,  -31,   24,  -48,  -80,
         -36,  -81,   13,  -43,   69,  -22,  -67,   65,   57,   13,   63,
         -19,   -5,  -43],
       [  44,   88,  -51,   84,   17,  -69,  -68,   75,   32,   61,    4,
          41,   69,   31,   94,   41,  100,   12,   91,  -85,   33,  -25,
          76,   58,  -58]])

In [10]:
arr2 = np.arange(1,364+1)
arr2_shape = np.shape(arr2)
print("arr2_shape: ", arr2_shape)
arr2

arr2_shape:  (364,)


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [12]:
arr2_reshaped_2d = np.reshape(arr2,(4,91))
arr2_reshaped_2d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91],
       [ 92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
        144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
        170, 171, 172, 173, 174, 175, 176, 177, 17

In [16]:
# indexing
print(arr2_reshaped_2d[3,17])

291


In [27]:
# slicing

sliced_array = arr2_reshaped_2d[2:]
sliced_array

array([[183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
        196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,
        209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,
        222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,
        235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,
        248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,
        261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273],
       [274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
        287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
        300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
        313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
        326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
        339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351,
        352, 353, 354, 355, 356, 357, 358, 359, 36

In [28]:
# extract a 1d array from the 2d array
sliced_array2 = sliced_array[1]
sliced_array2

array([274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
       287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
       300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
       313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
       326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
       339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351,
       352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364])

In [32]:
# aggregation functions

# np.sum()
sum_all_elements = np.sum(sliced_array2)
print("The sum of all elements of sliced_array2 is: ",sum_all_elements)

#np.mean()
mean = np.mean(sliced_array2)
print("The mean of all elements of sliced_array2 is: ",mean)

#median()
median = np.median(sliced_array2)
print("The median of all elements of sliced_array2 is: ",median)

# np.std()
std = np.std(sliced_array2)
print("The standard deviation of all elements of sliced_array2 is: ",std)

The sum of all elements of sliced_array2 is:  29029
The mean of all elements of sliced_array2 is:  319.0
The median of all elements of sliced_array2 is:  319.0
The standard deviation of all elements of sliced_array2 is:  26.267851073127396
