In [1]:
import numpy as np

In [12]:
# matrix random creation

matrix = np.random.randint(-100, 100, size=(13, 10))
# print(matrix)
matrix.sort()
print(matrix)

[[-98 -79 -52 -42 -25   7  32  56  75  80]
 [-67 -63 -59 -45 -27  -7  18  23  23  62]
 [-98 -91 -59 -57 -17  -1   8  12  26  34]
 [-91 -89 -85 -21  -9  -4  17  25  69  75]
 [-41 -33 -28 -19  -2  12  32  50  73  82]
 [-99 -91 -77 -61 -18  19  25  36  49  71]
 [-91 -61 -54 -52 -41  -9  -8  31  39  67]
 [-90 -12   1   9  28  45  52  81  88  94]
 [-96 -73 -54 -19 -13  -3   8  28  55  99]
 [-98 -72 -55   9  23  52  61  80  84  91]
 [-99 -66 -46 -28   5  19  24  43  55  82]
 [-68 -58 -51 -23   1  25  36  40  46  93]
 [-97 -72 -63 -53 -31 -25 -13  42  80  86]]


In [21]:
# extract the percentiles
# in a sorted list, if 0 is initial value and 100 is final value
# percentiles are were the values are divided in 100 parts
percentiles = [0, 25, 50, 75, 100]

# percentile 50 is the median

In [23]:
# note: you must take into account that the percentile is a value, not
# a position in the list nor a value in the list
percentile_50_matrix_as_array = np.percentile(matrix, percentiles[2])
percentile_50_matrix_as_array

-1.5

In [30]:
for p in percentiles[2:3]:
    values = np.percentile(matrix, p, axis=1)
    print(f'percentile {p} is {values}')

percentile 50 is [ -9.  -17.   -9.   -6.5   5.    0.5 -25.   36.5  -8.   37.5  12.   13.
 -28. ]


In [34]:
arr1 = np.random.randint(1, 100, size=120)
arr1

array([15, 68, 85, 12,  5, 87, 14, 33,  2, 48,  1, 82, 70, 59, 14, 22, 79,
       51,  2, 89, 79, 51, 30, 53, 34, 56, 80, 96, 68, 55, 73, 99, 13, 34,
       87, 12, 36, 32, 22, 62, 63, 65, 64, 19, 92, 97, 65, 44, 67, 54, 98,
       92, 99, 28, 26,  8, 43, 12, 58,  4, 13, 41,  1, 61, 83, 64, 32, 56,
       34, 94, 96, 78, 87, 29, 45, 23, 55, 36, 85,  4,  7, 39, 79, 37, 75,
       43, 35,  3, 27, 67, 23,  7,  3,  4,  9, 32, 52, 37, 74, 73, 74, 93,
       16, 73,  3, 16, 26, 24, 47, 60, 57,  9, 79, 87, 93, 33, 97, 23, 39,
       60])

In [40]:
# std is the std deviation, sqrt of variance. Avg distance between each
# value and the mean
# mean is the average of the values
# median is the value in the middle of the values
st1 = np.std(arr1)
median1 = np.median(arr1)
average1 = np.mean(arr1)
variance1 = np.var(arr1)
print('Average: ', average1) 
print('Median: ', median1)
print('Std: ', st1)
print('Variance: ', variance1)

Average:  48.0
Median:  47.5
Std:  29.785063370756827
Variance:  887.15
