In [1]:
import numpy as np

In [4]:
# trnaspose is a method for reshaping the array without copying it
arr = np.arange(15).reshape(3,5)
print('array: \n', arr)
print('array.T: \n', arr.T)
dot = np.dot(arr, arr.T)
print('dot product: \n', dot)

array: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
array.T: 
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
dot product: 
 [[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
