In [1]:
import numpy as np

In [3]:
# ufun could be exp, sqrt, sin, cos, floor, etc...
# they are element wise
arr = np.arange(25)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [6]:
# squared root
sqr_root = np.sqrt(arr)
print('Squared root arr: \n', sqr_root)

# exponent
exponent_arr = np.exp(arr)
print('Exponent arr: \n', exponent_arr)

# floor
arr2 = np.random.randn(7,4)
print('array: \n',arr2)
floor_arr = np.floor(arr2)
print('floor_array: \n',floor_arr)

Squared root arr: 
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563
 4.24264069 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152
 4.89897949]
Exponent arr: 
 [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06
 8.88611052e+06 2.41549528e+07 6.56599691e+07 1.78482301e+08
 4.85165195e+08 1.31881573e+09 3.58491285e+09 9.74480345e+09
 2.64891221e+10]
array: 
 [[-0.30462302  1.350295    0.76415686  1.46667481]
 [-1.93112709  2.26294785  1.5918532  -0.49833929]
 [ 1.80146147 -2.14950894  0.78013038  0.48253719]
 [-0.88196209  0.94812401  1.44266199  0.13555827]
 [-0.09475908  1.47032182  1.34001716 -0.27961899]
 [ 0.51977774 -2.05678848  1.5602096