In [1]:
import numpy as np

In [3]:
# where function is a vectorized version of x if cond, else y:

xarr = np.array([1.1,1.2,1.3,1.4,1.5,1.6])
yarr = np.array([1.0,2.0,3.1,4.2,5.3,6.4])
cond = np.array([False, True, False, False, True, False])

result = np.where(cond,xarr,yarr)
print('result(prints the x values where the cond is true. if not, print y) = \n',result)

result(prints the x values where the cond is true. if not, print y) = 
 [1.  1.2 3.1 4.2 1.5 6.4]


In [2]:
# Suppose you had a matrix of randomly generated data and you wanted
# to replace all positive values with 2 and all negative values with 
# –2. This is very easy to do with np.where:

arr = np.random.randn(4,4)
print('arr: \n', arr)

arr: 
 [[-0.15068564 -1.46245175 -0.66120498 -0.24783477]
 [ 1.05585988  0.42367657 -0.11561877  0.682643  ]
 [-0.35934144 -1.24100907 -0.79863511 -0.29531294]
 [ 0.08106159 -0.47783528  1.89835251 -0.02963481]]


In [6]:
# here we defined the values that correspond to the condition
bool_arr = arr > 0
print('bool_arr; \n', bool_arr)

bool_arr; 
 [[False False False False]
 [ True  True False  True]
 [False False False False]
 [ True False  True False]]


In [7]:
# use of where function
processed_arr = np.where(bool_arr,10,-2)
print(processed_arr)

[[-2 -2 -2 -2]
 [10 10 -2 10]
 [-2 -2 -2 -2]
 [10 -2 10 -2]]
