In [1]:
import numpy as np

In [6]:
arr = np.zeros(10)
arr1 = np.zeros((5,8))
arr2 = np.zeros((3,4,2))
print(arr,'\n\n',arr1,'\n\n',arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] 

 [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
