In [1]:
import numpy as np

In [6]:
arr = np.zeros(10)
arr1 = np.zeros((5,8))
arr2 = np.zeros((3,4,2))
print(arr,'\n\n',arr1,'\n\n',arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] 

 [[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [6]:
# negative values to zero
data = np.random.randn(7,4)
data[data < 0] = 0
print('data: \n',data)

data: 
 [[0.         0.46829915 0.14002632 0.        ]
 [1.89418348 0.         0.         0.2923469 ]
 [0.         0.         0.         1.70480837]
 [0.         1.04997415 0.         0.        ]
 [0.86392546 0.89892068 1.5036874  0.23195474]
 [0.         0.         0.         2.08475076]
 [0.93038633 0.         0.34084442 0.        ]]
